### ISSUE TITLE
Migrating from mLab to MongoDB Atlas

### ISSUE THREAD

**Issue by icyflame** [metakgp/leprechaun#14]
mLab is being [deprecated][1]. We need to migrate to another MongoDB cloud provider.

The recommended alternative seems to be Atlas, offered by MongoDB cloud.

Migration guide: https://docs.mlab.com/how-to-migrate-sandbox-heroku-addons-to-atlas/#b-connect-your-atlas-organization-to-the-source-mlab-account

[1]: https://hello.heroku.com/webmail/36622/998662117/827055fd728b579753e6053d8b738ecb2805c48d335e104848ee3d05071a97f6

**Comment by icyflame** [comment]
All times are in JST (UTC+9)

1. Create an account on https://www.mongodb.com/cloud/atlas/signup
1. Open Heroku dashboard and open the mLab add-on page (this automatically logs you into the mLab account)
1. Connect Atlas account to mLab
1. 23:42: Put the target application in Maintenance mode

	![image](https://user-images.githubusercontent.com/3668034/98444070-02541880-2153-11eb-8caf-69e623c1a84c.png)

1. Start the `Configuration migration` wizard on Atlas
1. 23:44: Complete the Configuration migration subsection of the wizard (Just tapping on the green button a few times without changing anything on the screen)

	![image](https://user-images.githubusercontent.com/3668034/98444129-52cb7600-2153-11eb-89a1-70c24971e6b0.png)

	> Scroll down and click the green “Confirm Target and Continue” button to create a free Atlas database (M0 tier). It will take about 7-9 minutes for the Atlas database to be created.

	Looks like this step will take a few minutes;

1. 23:48: Configure the migration and run a "test run" (recommended)

	![image](https://user-images.githubusercontent.com/3668034/98444245-eef57d00-2153-11eb-8d67-87b05cafe474.png)

	![image](https://user-images.githubusercontent.com/3668034/98444189-bc4b8480-2153-11eb-86ed-c8707c2307d9.png)

**Comment by icyflame** [comment]
Stuck on the `Confirm Connectivity Step`

```sh

$ docker run --rm --name mongo -it mongo:latest mongo "$MONGODB_URI"
MongoDB shell version v4.4.1
connecting to: mongodb://...<REMOVED>


*** It looks like this is a MongoDB Atlas cluster. Please ensure that your IP whitelist allows connections from your network.

Error: can't connect to new replica set master [REMOVED:27017], err: AuthenticationFailed: bad auth : Authentication failed. :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
```

**Comment by icyflame** [comment]
I brought the back out of maintenance mode while I get through this `Confirm Connectivity Step`

**Comment by icyflame** [comment]
Trying to connect using the same version as the MongoDB that's present on the cluster (4.2.10);

***

Found and fixed the issue! :white_check_mark: 

```sh
$ echo $MONGODB_URI
mongodb+srv://USERNAME:<password>@PATH/DATABASE?retryWrites=true&w=majority

$ echo $MONGODB_URI
mongodb+srv://USERNAME:PASSWORD@PATH/DATABASE?retryWrites=true&w=majority
```

In the connection string that I copied from Heroku, the password was not present. It had the literal string `<password>`. I generated a password on the Atlas website: `Security > Database Access > Admin User > Edit > Generate Password` 

![image](https://user-images.githubusercontent.com/3668034/98444938-15b5b280-2158-11eb-83fb-f362f53b0e58.png)

**Comment by icyflame** [comment]
Confirmed connectivity :white_check_mark: 

```sh
$ docker run --rm --name mongo -it mongo:4.2.10 mongo "$MONGODB_URI"
MongoDB shell version v4.2.10
connecting to: mongodb://<CONNECT_STRING>?authSource=admin&compressors=disabled&gssapiServiceName=mongodb&replicaSet=atlas-gvc7sl-shard-0&retryWrites=true&ssl=true&w=majority
2020-11-07T15:20:18.792+0000 I  NETWORK  [js] Starting new replica set monitor for CLUSTER1,CLUSTER2,CLUSTER3
2020-11-07T15:20:18.792+0000 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to CLUSTER1
2020-11-07T15:20:18.792+0000 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to CLUSTER2
2020-11-07T15:20:18.792+0000 I  CONNPOOL [ReplicaSetMonitor-TaskExecutor] Connecting to CLUSTER3
2020-11-07T15:20:19.720+0000 I  NETWORK  [ReplicaSetMonitor-TaskExecutor] Confirmed replica set for CLUSTER1,CLUSTER2,CLUSTER3
Implicit session: session { "id" : UUID("a4330377-220e-4229-a1d1-07bda7863d71") }
MongoDB server version: 4.2.10
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
        https://docs.mongodb.com/
Questions? Try the MongoDB Developer Community Forums
        https://community.mongodb.com
2020-11-07T15:20:21.479+0000 I  STORAGE  [main] In File::open(), ::open for '/home/mongodb/.mongorc.js' failed with No such file or directory
Error while trying to show server startup warnings: user is not allowed to do action [getLog] on [admin.]
MongoDB Enterprise atlas-gvc7sl-shard-0:PRIMARY> db.people.findOne();
{
        "_id" : ObjectId("5a4e28528fdf63769d0d3f64"),
        "roll" : "13ME33012",
        "email" : "[FILTERED]",
        "verifier" : "[FILTERED]",
        "emailtoken" : "[FILTERED]",
        "linksuffix" : "[FILTERED]",
        "step1complete" : true,
        "step1completedat" : ISODate("2018-01-04T13:14:14.038Z"),
        "step2complete" : true,
        "step2completedat" : ISODate("2018-01-04T13:12:50.541Z")
}
MongoDB Enterprise atlas-gvc7sl-shard-0:PRIMARY> db.people.count();
65
MongoDB Enterprise atlas-gvc7sl-shard-0:PRIMARY>
bye
2020-11-07T15:21:04.036+0000 E  -        [main] Error saving history file: FileOpenFailed: Unable to open() file /home/mongodb/.dbshell: No such file or directory
```

Looks like the database has already been migrated successfully to Atlas! :white_check_mark:

**Comment by icyflame** [comment]
Add the new connection string as the new env variable `ATLAS_MONGODB_URI`

```sh
$ heroku config:set ATLAS_MONGODB_URI=[FILTERED] -a leprechaun-metakgp
 ›   Warning: heroku update available from 7.39.0 to 7.47.0.
Setting ATLAS_MONGODB_URI and restarting ⬢ leprechaun-metakgp... done, v41
ATLAS_MONGODB_URI: [FILTERED]

$ heroku config -a leprechaun-metakgp
 ›   Warning: heroku update available from 7.39.0 to 7.47.0.
=== leprechaun-metakgp Config Vars
ATLAS_MONGODB_URI: [FILTERED]
AUTH_TOKEN:        [FILTERED]
BASE_LINK:         [FILTERED]
DB_NAME:           [FILTERED]
FROM_EMAIL:        [FILTERED]
FROM_NAME:         [FILTERED]
MONGODB_URI:       [FILTERED]
SENDGRID_API_KEY:  [FILTERED]
```

**Comment by icyflame** [comment]
![image](https://user-images.githubusercontent.com/3668034/98445082-0daa4280-2159-11eb-95ac-b91e1a986304.png)

Ready for migration; I put the app in maintenance mode;

**Comment by icyflame** [comment]
Migration completed; I changed the application code to look at only the new DB variable

https://github.com/metakgp/leprechaun/commit/4b5de19efc9db1800384e435fdaa741007513ca0

**Comment by icyflame** [comment]
Looks like application is having trouble connecting to this new MongoDB

```
2020-11-07T15:30:55.242705+00:00 app[api]: Release v42 created by user mail@siddharthkannan.in
2020-11-07T15:30:55.424356+00:00 heroku[web.1]: Restarting
2020-11-07T15:30:55.444981+00:00 heroku[web.1]: State changed from up to starting
2020-11-07T15:30:56.144985+00:00 heroku[web.1]: Starting process with command `leprechaun`
2020-11-07T15:30:56.357398+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-11-07T15:30:56.455798+00:00 heroku[web.1]: Process exited with status 143
2020-11-07T15:30:59.000493+00:00 app[web.1]: panic: unsupported connection URL option: retryWrites=true
2020-11-07T15:30:59.000551+00:00 app[web.1]:
2020-11-07T15:30:59.000645+00:00 app[web.1]: goroutine 1 [running]:
2020-11-07T15:30:59.000723+00:00 app[web.1]: main.DialDB(0x7d087e)
2020-11-07T15:30:59.000832+00:00 app[web.1]: /tmp/tmp.yuEgqp34LW/.go/src/github.com/icyflame/leprechaun/db.go:14 +0xad
2020-11-07T15:30:59.000884+00:00 app[web.1]: main.init.ializers()
2020-11-07T15:30:59.000996+00:00 app[web.1]: /tmp/tmp.yuEgqp34LW/.go/src/github.com/icyflame/leprechaun/main.go:10 +0x22
2020-11-07T15:30:59.050064+00:00 heroku[web.1]: Process exited with status 2
2020-11-07T15:30:59.098095+00:00 heroku[web.1]: State changed from starting to crashed
2020-11-07T15:30:59.102300+00:00 heroku[web.1]: State changed from crashed to starting
2020-11-07T15:30:59.619620+00:00 heroku[web.1]: Starting process with command `leprechaun`
2020-11-07T15:31:02.596028+00:00 app[web.1]: panic: unsupported connection URL option: w=majority
2020-11-07T15:31:02.596044+00:00 app[web.1]:
2020-11-07T15:31:02.596051+00:00 app[web.1]: goroutine 1 [running]:
2020-11-07T15:31:02.596052+00:00 app[web.1]: main.DialDB(0x7d087e)
2020-11-07T15:31:02.596052+00:00 app[web.1]: /tmp/tmp.yuEgqp34LW/.go/src/github.com/icyflame/leprechaun/db.go:14 +0xad
2020-11-07T15:31:02.596058+00:00 app[web.1]: main.init.ializers()
2020-11-07T15:31:02.596087+00:00 app[web.1]: /tmp/tmp.yuEgqp34LW/.go/src/github.com/icyflame/leprechaun/main.go:10 +0x22
2020-11-07T15:31:02.650252+00:00 heroku[web.1]: Process exited with status 2
2020-11-07T15:31:02.713442+00:00 heroku[web.1]: State changed from starting to crashed
2020-11-07T15:31:13.000000+00:00 app[api]: Build succeeded
2020-11-07T15:31:37.219119+00:00 app[api]: Set maintenance mode off by user mail@siddharthkannan.in
2020-11-07T15:31:43.121092+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=leprechaun.metakgp.org request_id=f520a829-f9f1-4b03-94fa-41ad6fc58e38 fwd="220.213.59.37,162.158.118.90" dyno= connect= service= status=503 bytes= protocol=http
2020-11-07T15:32:02.460228+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=leprechaun.metakgp.org request_id=a291034c-80ed-4b99-88fb-a8231ad38420 fwd="220.213.59.37,162.158.118.90" dyno= connect= service= status=503 bytes= protocol=http
```

I will reset to mLab DB while I fix the issue

**Comment by icyflame** [comment]
Driver needs to support at least MongoDB 3.6 with SSL

https://github.com/globalsign/mgo

https://docs.mlab.com/troubleshooting-atlas-connection-issues/#5-ensure-that-the-version-of-your-mongodb-driver-is-compatible-with-at-least-mongodb-36x

I can't find any other Go driver which supports Mongo DB 4.x

**Comment by icyflame** [comment]
Alright, I was able to make it work by replacing `mgo.v2` with it's forked version! :white_check_mark: 

https://github.com/metakgp/leprechaun/commit/99b27a88183eae3e0ed949e85896949311d4e526

**Comment by icyflame** [comment]
`mongodb+srv` connection string does not work. (driver too old and probably doesn't support that)

I will use the connection string for older versions.

**Comment by icyflame** [comment]
I didn't include the new package in the list of dependencies managed by govendor inside vendor/vendor.json

```sh
remote: Building source:
remote:
remote: -----> Go app detected
remote: -----> Fetching stdlib.sh.v8... done
remote: -----> Checking vendor/vendor.json file.
remote:  !!    The 'heroku.goVersion' field is not specified in 'vendor/vendor.json'.
remote:  !!
remote:  !!    Defaulting to go1.12.17
remote:  !!
remote:  !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-govendor#build-configuration
remote:  !!
remote: -----> Using go1.12.17
remote:  !!    Installing package '.' (default)
remote:  !!
remote:  !!    To install a different package spec set 'heroku.install' in 'vendor/vendor.json'
remote:  !!
remote:  !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-govendor#build-configuration
remote:  !!
remote: -----> Fetching any unsaved dependencies (govendor sync)
remote: -----> Running: go install -v -tags heroku .
remote: db.go:6:2: cannot find package "github.com/globalsign/mgo" in any of:
remote:         /tmp/tmp.0SAsRQWCYA/.go/src/github.com/icyflame/leprechaun/vendor/github.com/globalsign/mgo (vendor tree)
remote:         /tmp/codon/tmp/cache/go1.12.17/go/src/github.com/globalsign/mgo (from $GOROOT)
remote:         /tmp/tmp.0SAsRQWCYA/.go/src/github.com/globalsign/mgo (from $GOPATH)
remote: handlers.go:14:2: cannot find package "github.com/globalsign/mgo/bson" in any of:
remote:         /tmp/tmp.0SAsRQWCYA/.go/src/github.com/icyflame/leprechaun/vendor/github.com/globalsign/mgo/bson (vendor tree)
remote:         /tmp/codon/tmp/cache/go1.12.17/go/src/github.com/globalsign/mgo/bson (from $GOROOT)
remote:         /tmp/tmp.0SAsRQWCYA/.go/src/github.com/globalsign/mgo/bson (from $GOPATH)
remote:  !     Push rejected, failed to compile Go app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to leprechaun-metakgp.
remote:
To https://git.heroku.com/leprechaun-metakgp.git
 ! [remote rejected] prod -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/leprechaun-metakgp.git'
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
```

**Comment by icyflame** [comment]
Accidentally closed the issue;

Restarted Heroku dyno with connection string for the Atlas DB :white_check_mark: 

The app is up and working: https://leprechaun.metakgp.org/

**Comment by icyflame** [comment]
![image](https://user-images.githubusercontent.com/3668034/98446011-56b0c580-215e-11eb-801e-35a6c855dc92.png)

I will leave the database on mLab until tomorrow morning and then delete the add-on from there too :ok_man:

**Comment by kshitij10496** [comment]
Wow! This thread reads like a blog post I always would want to refer for migrations to MongoDB Atlas. ❤️
